default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude_types: [html]
        additional_dependencies:
          - prettier@2.7.1
          - "@shopify/prettier-plugin-liquid"

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.15.0
    hooks:
      - id: stylelint
        exclude_types: [sass]
        additional_dependencies:
          ["stylelint", "stylelint-prettier", "stylelint-config-prettier"]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.7
    hooks:
      - id: djlint-django
        exclude: _layouts/compress.html
      - id: djlint-django
        args: [".", "--reformat"]
        exclude: _layouts/compress.html

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
