default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.4
    hooks:
      - id: commitizen

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.4
    hooks:
      - id: prettier
        exclude_types: [html, markdown]
        additional_dependencies:
          - prettier@2.7.1
          - "@shopify/prettier-plugin-liquid"

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v17.14.0
    hooks:
      - id: stylelint
        exclude_types: [sass]
        additional_dependencies: ["stylelint"]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.40.2
    hooks:
      - id: djlint-django
        exclude: _layouts/compress.html
      - id: djlint-django
        args: ["--reformat"]
        exclude: _layouts/compress.html

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
